version: '3'
services:
  selfie-thread-bot:
    container_name: selfie-thread-bot
    restart: always
    build: .
    links:
      - stb-mongo
  stb-mongo:
    container_name: stb-mongo
    restart: always
    image: mongo
    volumes: 
      - /data/mongo