version: '3'
services:
  app:
    container_name: selfie-thread-bot
    restart: always
    build: .
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes: 
      - /data/mongo